baseURL = "https://nav.xseven.top"
languageCode = "zh-CN"
title = "X7 开发&设计 网址导航"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "docs"


[params]
    author        = "realxx7"
    description   = "开发与设计 网址导航 | BY IT&ART 爱好者X7"
    siteurl       = "./"
    about         = "./about"   # 左侧导航栏的"关于导航"页面(./about)
    communicate   = "./communicate" # 左侧导航栏的"交流区"页面
    repository    = "https://github.com/realxx7/webstack"  
    enablePreLoad = true		    		           # 网站完全打开前预加载动画
    textPreLoad   = "X7开发&设计 网址导航" 		           # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false                                          # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			   # 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"             # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
#   baiduhmid     = 'efccc04cb44fc49faddac5876180b369'             # 百度统计 hm.src 的 ID

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.cdn]
    fontawesome     = "https://cdn.staticfile.org/font-awesome/6.2.0"
    

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"		#搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站为个人网址收藏汇总，内容源自互联网，如有内容侵犯了你的权益，可联系删除相关内容<br/>&copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo)'
    busuanzi  = true